apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dogs
  name: dogs-pod
spec:
  containers:
  - image: xyz
    name: dogs-container
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always